authors:
    resource: "@AuthorsBundle/Controller/"
    type:     annotation
    prefix:   /

books:
    resource: "@BooksBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
