services:
#    authors.example:
#        class: Stormtech\AuthorsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    authors.business:
        class: Stormtech\AuthorsBundle\Service\AuthorsBusiness

    authors.app_messages:
        class: Stormtech\AuthorsBundle\Service\AuthorsAppMessages
