<?php

namespace Stormtech\BooksBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Ordering Books by fields.
     * 
     * @param array $fields Table fields to ordering. Eg.: ['field1', ...]
     * @param array $fieldsOrders Order fields. Eg.: ['field1' => 'ASC', ...]
     * @return array
     */
    public function findAllOrderBy(array $fields, array $fieldsOrders)
    {
        $qb = $this->createQueryBuilder('b');
        $qb->join('b.authors', 'a');

        foreach ($fields as $field) {
            if ($field == 'author') {
                $qb->addOrderBy('a.name', $fieldsOrders[$field]);
            }
            else {
                $qb->addOrderBy('b.' . $field, $fieldsOrders[$field]);
            }

        }

        return $qb->getQuery()->getResult();
    }
}